### ISSUE TITLE
Sooritatud etteütluse tulemuste salvestamine CSV-faili

### ISSUE THREAD

**Issue by tammets** [centre-for-educational-technology/e-etteytlus#14]
CSV-faili on võimalik alla laadida Etteütluste lehelt. CSV-fail koosneb:

nimi / e-post / kuupäev / kontrollteksti pealkiri / vigased tähemärgid / vigased sõnad / vigased laused / tähemärgid kokku / sõnad kokku / laused kokku / tulemus protsentides

![csv](https://cloud.githubusercontent.com/assets/380007/15814825/b3a815b8-2bd1-11e6-8154-424c7b5e4246.png)

**Comment by pjotrsavitski** [comment]
Needs testing.
